#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: node-express
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — a failing command inside a pipeline is otherwise silent.
#   - `sha256sum` for lockfile hashing — never hand-rolled (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — always writable inside the sandbox.
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — the sentinel
#     survives reboots but install output dirs may not on fresh tmpfs, so never
#     skip on a clean directory.
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".

set -euo pipefail

# === Bash version guard ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === Already-up fast path (#219) ===
READY_PORTS="3000"
DEV_STATE="/tmp/pivota-dev-boot-state"
dev_boot_state() {
  printf '%s|%s' \
    "$(git rev-parse HEAD 2>/dev/null || echo no-git)" \
    "$(docker compose config 2>/dev/null | sha256sum 2>/dev/null | cut -d' ' -f1)"
}
dev_ports_answering() {
  local p ok=1
  [ -n "${READY_PORTS// /}" ] || return 1
  for p in $READY_PORTS; do
    if (exec 3<>"/dev/tcp/127.0.0.1/$p") 2>/dev/null; then exec 3>&-; ok=0; fi
  done
  return $ok
}
dev_compose_healthy() {
  docker compose config --services >/dev/null 2>&1 || return 0
  local rows
  rows="$(docker compose ps --all 2>/dev/null | tail -n +2 || true)"
  [ -n "$rows" ] || return 1
  ! printf '%s\n' "$rows" | grep -qiE 'restarting|unhealthy|exited \([1-9]'
}
if [[ "${PIVOTA_DEV_FORCE_RESTART:-}" != "1" ]] \
   && [[ -f "$DEV_STATE" ]] \
   && [[ "$(cat "$DEV_STATE" 2>/dev/null)" == "$(dev_boot_state)" ]] \
   && dev_ports_answering \
   && dev_compose_healthy; then
  echo "[pivota] dev stack already up on port(s) ${READY_PORTS} with unchanged compose config and HEAD — skipping restart (set PIVOTA_DEV_FORCE_RESTART=1 to override)"
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: node-express)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
export PORT="${PORT:-3000}"
# Node's server.listen(port) with no host arg already binds all interfaces
# (:: / 0.0.0.0), so most express apps are preview-reachable out of the box.
# HOST=0.0.0.0 covers the apps that explicitly do app.listen(port, process.env.HOST)
# or default the host to 'localhost' (which can resolve to ::1 and refuse the
# preview proxy's IPv4 connect — runtime-environment.md §2).
export HOST=0.0.0.0
# DO NOT set NODE_ENV=production here: it makes npm omit devDependencies, which
# strips nodemon/ts-node/tsc and breaks the dev runner (runtime-environment.md §4).
# Express has no host-header allowlist — nothing to relax.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === D-11.6 (#510): load .env into THIS process's environment ===
if [[ -f .env ]]; then
  echo "[pivota] loading .env into the environment"
  PIVOTA_ENV_KEEP="$(mktemp)"
  while IFS= read -r _pivota_key; do
    if [[ -n "${!_pivota_key+x}" ]]; then
      declare -p "$_pivota_key" 2>/dev/null || true
    fi
  done < <(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)=.*/\2/p' .env | sort -u) \
       > "$PIVOTA_ENV_KEEP"
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
  # shellcheck disable=SC1090
  . "$PIVOTA_ENV_KEEP"
  rm -f "$PIVOTA_ENV_KEEP"
  unset PIVOTA_ENV_KEEP _pivota_key
fi

# === D-11.7 (#510): workspace-hoisted binaries on PATH ===
export PATH="$PWD/node_modules/.bin:$PATH"

# === Optional pre-exec snippet ===
# (none) — express needs no system-level pre-install setup.

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci --include=dev --prefer-offline 2>/dev/null || npm install --include=dev'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?
  if (( rc == 0 )); then
    return 0
  fi
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps (peer conflict force-resolved; runtime incompatibility possible)"
    local rc2=0
    npm install --legacy-peer-deps || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — a dependency's peer range is unsatisfied; fix package.json (this is a real bug, not just a warning)"
      return 0
    fi
    rc=$rc2
  fi
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start; resolve the dependency conflict in the manifest" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='HAS_SCRIPT() { node -e "process.exit(((require(\"./package.json\").scripts||{})[\"$1\"])?0:1)" 2>/dev/null; }
if [ -n "${DATABASE_URL:-}" ]; then
  SEED=""
  for s in migrate:schema migrate db:migrate migrate:deploy migrate:prod prisma:migrate db:push; do
    if HAS_SCRIPT "$s"; then SEED="$s"; break; fi
  done
  if [ -n "$SEED" ]; then
    echo "[pivota] seeding DB via the declared project script: npm run $SEED"
    npm run "$SEED" || echo "[pivota] npm run $SEED returned non-zero (continuing)"
  elif [ -f prisma/schema.prisma ]; then
    echo "[pivota] no migrate script declared; seeding via prisma"
    npx prisma generate 2>&1 | tail -2 || true
    if [ -d prisma/migrations ]; then
      npx prisma migrate deploy || echo "[pivota] prisma migrate deploy non-zero (continuing)"
    else
      npx prisma db push --skip-generate --accept-data-loss || echo "[pivota] prisma db push non-zero (continuing)"
    fi
  else
    echo "[pivota] WARNING: DATABASE_URL is set but no migrate script or prisma schema found — the app may serve on an EMPTY database"
  fi
fi
if HAS_SCRIPT dev; then exec npm run dev
elif HAS_SCRIPT start:dev; then exec npm run start:dev
elif HAS_SCRIPT start; then
  if node -e '\''process.exit(/\b(dist|build)\//.test((require("./package.json").scripts||{}).start||"")?0:1)'\'' && [ ! -d dist ] && [ ! -d build ]; then
    echo "[pivota] start script targets a compiled entry; building first"
    npm run build || echo "[pivota] npm run build returned non-zero (continuing)"
  fi
  exec npm start
else
  exec node "$(node -e '\''console.log(require("./package.json").main || "index.js")'\'')"
fi'

# #219: record boot state
dev_boot_state > "$DEV_STATE" 2>/dev/null || true

ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

exit 1
# === END PIVOTA PREAMBLE ===
